name: 'Docker Build and Push'
on: 

  workflow_dispatch:
    
    inputs:

      BuildDocker:
        description: Build Docker
        type: boolean
        required: false
        default: false

      RunDocker:
          description: Run Docker
          type: boolean
          required: false
          default: false

env:
  MESSAGE: ${{ vars.message }}
  DATE: $(date +'%Y%m%d')
  DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/helloworld-${{ github.ref_name }}

jobs:
  
  set-tag:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.BuildDocker == 'true'
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.TAG }}
    steps:

      - name: Set Tag
        id: set_tag
        run: echo "TAG=${{ env.DATE }}-${{ vars.version }}" >> "$GITHUB_OUTPUT"
      
  build-docker:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.BuildDocker == 'true'
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    needs: [ set-tag ]
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        run: docker build -t helloworld .

      - name: Docker Tag and Push
        run: |
          docker tag helloworld ${{ env.DOCKER_REPO }}:${{ needs.set-tag.outputs.tag }}
          docker push ${{ env.DOCKER_REPO }}:${{ needs.set-tag.outputs.tag }}

      - name: Increment Environment Variable
        if: success()
        uses: MandalAutomations/Increment-Environment-Variable@v1
        with:
          Name: "VERSION"
          EnvironmentName: ${{ github.ref_name }}
          RepoId: ${{ github.repository_id }}
          Token: ${{ secrets.PAT_TOKEN }}

  run-docker:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.RunDocker == 'true' && github.event.inputs.BuildDocker == 'true'
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    needs: [ set-tag, build-docker ]
    steps:

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Docker
        run: docker run -e MY_VARIABLE="${{ env.MESSAGE }}" ${{ env.DOCKER_REPO }}:${{ needs.set-tag.outputs.tag }}