name: "Issue Close"
on:
  workflow_dispatch:

env:
    GH_TOKEN: ${{ github.token }}

jobs:
    closeBugs:
        name: Close all issues labeled "bug"
        runs-on: ubuntu-latest
        steps:
            # - name: Find all bugs
            #   id: bugs
            #   uses: lee-dohm/select-matching-issues@v1
            #   with:
            #     query: 'label:bug'
            #     token: ${{ secrets.PAT_TOKEN }}

            # - name: Close found issues
            #   run: cat ${{ steps.bugs.outputs.path }}

            - name: List all issues
              run: |
                echo "List all issues"
                echo "================"
                gh issue list --limit 1000 --state open --label bug --json number,title,url,labels > issues.json
                cat issues.json
        env:
            GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}