name: 'Hello World'
on: 
  # push:
  #   branches: [ "main" ]

  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        default: 'Hello World'

env:
  TAG: ${{ github.run_id }}
  MESSAGE: ${{ vars.message }}
  ##${{ github.event.inputs.message }}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/helloworld:${{ env.TAG }}

  create-file: 
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Create file
        run: |
          echo "Hello World" > hello.txt
          cat hello.txt

      - name: Upload file
        uses: actions/upload-artifact@v2
        with:
          name: hello.txt
          path: hello.txt

  run-docker:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Docker
        run: docker run -e MY_VARIABLE="${{ env.MESSAGE }}" ${{ secrets.DOCKERHUB_USERNAME }}/helloworld:${{ env.TAG }}