name: 'Hello World'
on: 
  # push:
  #   branches: [ "main" ]

  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        default: 'Hello World'
      RunDocker:
          description: Run Docker
          type: boolean
          required: false
          default: false
  
  schedule:
    - cron: '0 12 * * *'

env:
  TAG: ${{ github.run_id }}
  MESSAGE: ${{ vars.message }}
  ACTION: ${{ github.event_name }}

jobs:

  create-file: 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Echo message
      run: |
        echo "Message: ${{ env.ACTION }}"

    # - name: Configure Git
    #   run: |
    #     git config --global user.name "evanallen13"
    #     git config --global user.email "evanallen13@gmail"
        
    # - name: Make changes
    #   run: |
    #     git pull origin main
    #     echo "Updated content" >> myfile.txt
    #     git add myfile.txt
    #     git commit -m "Auto commit: Updated myfile.txt"

    # - name: Push changes
    #   run: |
    #     git push origin main

  build-docker:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.RunDocker
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/helloworld:${{ env.TAG }}

  run-docker:
    runs-on: ubuntu-latest
    needs: [ build-docker, create-file]
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Docker
        run: docker run -e MY_VARIABLE="${{ env.MESSAGE }}" ${{ secrets.DOCKERHUB_USERNAME }}/helloworld:${{ env.TAG }}