name: "Multi-Test Deploy"
on:
  workflow_dispatch:

jobs:

    run: 
        runs-on: [ ubuntu-latest, macos-latest, windows-latest ]
        steps:
            - name: Run
            run: |
                echo "Hello World"