name: "Multi-Test Deploy"
on:
  workflow_dispatch:

jobs:

    run:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
              enviornments: ["main", "test", "uat"]
              somthing: ["one", "two", "three"]
        steps:
            - name: Echo Hello
              run: echo "Hello Workd"