name: "Multi-Test Deploy"
on:
  workflow_dispatch:

jobs:

    run:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
              enviornments: ["main", "test", "uat"]
        steps:

            - name: Increment Environment Variable
              if: ${{ matrix.enviornments == 'main' }}
              run: echo "This is main"