name: "Multi-Test Deploy"
on:
  workflow_dispatch:

jobs:

    run:
        runs-on: [ ]
        strategy:
            matrix:
              enviornments: [ubuntu-18.04, ubuntu-20.04]
        steps:

            - name: Increment Environment Variable
              if: ${{ matrix.enviornments == 'main' }}
              run: echo "This is main"