name: "Multi-Test Deploy"
on:
  workflow_dispatch:

jobs:

    run:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              enviornments: ["main", "test", "uat"]
        steps:

            - name: checkout
              uses: actions/checkout@v2

            - name: Increment Environment Variable
              run: |
                chmod a+x ./SayHello.sh
                ./SayHello.sh ${{ matrix.enviornments}}