name: Test Octokit
on:
  push:
    branches:
      - main

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
            route: GET /repositories/{repoId}/environments${environmentName}/variables/{name}
            repoId: ${{ github.repository_id }}
            environmentName: "uat"
            name: "version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"