
name: 'reset-version'
on: 
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:

  reset:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        enviornments: ["main", "test", "uat"]

    steps:
      - name: "Set Variable"
        uses: action-pack/set-variable@v1
        with:
          name: 'VERSION'
          value: '1'
          token: ${{ secrets.PAT_TOKEN }}

      - name: Increment Environment Variable
        uses: MandalAutomations/Increment-Environment-Variable@v3
        with:
          Name: "VERSION"
          EnvironmentName: ${{ matrix.enviornments }}
          RepoId: ${{ github.repository_id }}
          Token: ${{ secrets.PAT_TOKEN }}