
name: 'reset-version'

on: 
    schedule:
        - cron: '0 0 * * *'

    workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
        - name: "Set Variable"
          uses: action-pack/set-variable@v1
          with:
            name: 'VERSION'
            value: '1'
            token: ${{ secrets.PAT_TOKEN }}