
name: 'reset-version'

on: 
    schedule:
        - cron: '0 * * * *'

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
        - name: "Set Variable"
          uses: action-pack/set-variable@v1
          with:
            name: 'MY_VARIABLE'
            value: 'Lorem ipsun dolor simit'
            token: ${{ secrets.PAT_TOKEN }}