
name: 'reset-version'
on: 
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:

  reset:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        enviornments: ["main", "test", "uat"]

    steps:
      
      - name: Update Environment Variable
        uses: MandalAutomations/Update-Environment-Variable@v6
        with:
          Name: "VERSION"
          Value: ${{ 1 }}
          EnvironmentName: ${{ matrix.enviornments }}
          RepoId: ${{ github.repository_id }}
          Token: ${{ secrets.PAT_TOKEN }}
