name: Automation Tests

on:
    workflow_dispatch:

jobs:

    something:
        runs-on: ubuntu-latest
        steps:

            - name: None
              if: github.event_name != 'schedule'
              run: echo "None"
